# Generated by Django 4.2.4 on 2023-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='composition',
            field=models.TextField(default='default composition', verbose_name='Состав букета'),
            preserve_default=False,
        ),
    ]
