# Generated by Django 4.2.4 on 2023-08-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультацию', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(choices=[('AM', '11:00 - 15:00'), ('PM', '15:00 - 20:00')], default='PM', max_length=20, verbose_name='Время доставки')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bot.catalog', verbose_name='Букет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order_set', to='bot.client', verbose_name='Клиент')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_order_set', to='bot.client', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
